package mouse

trait AllSharedSyntax
    extends AnySyntax
    with AnyFSyntax
    with OptionSyntax
    with BooleanSyntax
    with BooleanFSyntax
    with StringSyntax
    with TrySyntax
    with IntSyntax
    with LongSyntax
    with DoubleSyntax
    with PartialFunctionLift
    with MapSyntax
    with FOptionSyntax
    with FEitherSyntax
    with FNestedSyntax
    with TupleSyntax
